from conans import ConanFile


class BoostConan(ConanFile):
    name = "Boost"
    version = "1.65.1"
    settings = "os", "arch", "compiler", "build_type"
    short_paths = True
    url = "https://github.com/bincrafters/conan-boost"
    description = "Please visit http://www.boost_org/doc/libs/1_65_1/libs/libraries.htm"
    license = "www.boost_org/users/license.html"
    build_requires = "boost_generator/1.65.1@bincrafters/stable" 
    requires = "boost_accumulators/1.65.1@bincrafters/stable", \
        "boost_algorithm/1.65.1@bincrafters/stable", \
        "boost_align/1.65.1@bincrafters/stable", \
        "boost_any/1.65.1@bincrafters/stable", \
        "boost_array/1.65.1@bincrafters/stable", \
        "boost_asio/1.65.1@bincrafters/stable", \
        "boost_assert/1.65.1@bincrafters/stable", \
        "boost_assign/1.65.1@bincrafters/stable", \
        "boost_atomic/1.65.1@bincrafters/stable", \
        "boost_bimap/1.65.1@bincrafters/stable", \
        "boost_bind/1.65.1@bincrafters/stable", \
        "boost_chrono/1.65.1@bincrafters/stable", \
        "boost_circular_buffer/1.65.1@bincrafters/stable", \
        "boost_compatibility/1.65.1@bincrafters/stable", \
        "boost_compute/1.65.1@bincrafters/stable", \
        "boost_concept_check/1.65.1@bincrafters/stable", \
        "boost_config/1.65.1@bincrafters/stable", \
        "boost_container/1.65.1@bincrafters/stable", \
        "boost_context/1.65.1@bincrafters/stable", \
        "boost_conversion/1.65.1@bincrafters/stable", \
        "boost_convert/1.65.1@bincrafters/stable", \
        "boost_core/1.65.1@bincrafters/stable", \
        "boost_coroutine/1.65.1@bincrafters/stable", \
        "boost_coroutine2/1.65.1@bincrafters/stable", \
        "boost_crc/1.65.1@bincrafters/stable", \
        "boost_date_time/1.65.1@bincrafters/stable", \
        "boost_detail/1.65.1@bincrafters/stable", \
        "boost_disjoint_sets/1.65.1@bincrafters/stable", \
        "boost_dll/1.65.1@bincrafters/stable", \
        "boost_dynamic_bitset/1.65.1@bincrafters/stable", \
        "boost_endian/1.65.1@bincrafters/stable", \
        "boost_exception/1.65.1@bincrafters/stable", \
        "boost_fiber/1.65.1@bincrafters/stable", \
        "boost_filesystem/1.65.1@bincrafters/stable", \
        "boost_flyweight/1.65.1@bincrafters/stable", \
        "boost_foreach/1.65.1@bincrafters/stable", \
        "boost_format/1.65.1@bincrafters/stable", \
        "boost_function/1.65.1@bincrafters/stable", \
        "boost_function_types/1.65.1@bincrafters/stable", \
        "boost_functional/1.65.1@bincrafters/stable", \
        "boost_fusion/1.65.1@bincrafters/stable", \
        "boost_geometry/1.65.1@bincrafters/stable", \
        "boost_gil/1.65.1@bincrafters/stable", \
        "boost_graph/1.65.1@bincrafters/stable", \
        "boost_graph_parallel/1.65.1@bincrafters/stable", \
        "boost_hana/1.65.1@bincrafters/stable", \
        "boost_heap/1.65.1@bincrafters/stable", \
        "boost_icl/1.65.1@bincrafters/stable", \
        "boost_integer/1.65.1@bincrafters/stable", \
        "boost_interprocess/1.65.1@bincrafters/stable", \
        "boost_intrusive/1.65.1@bincrafters/stable", \
        "boost_io/1.65.1@bincrafters/stable", \
        "boost_iostreams/1.65.1@bincrafters/stable", \
        "boost_iterator/1.65.1@bincrafters/stable", \
        "boost_lambda/1.65.1@bincrafters/stable", \
        "boost_level5group/1.65.1@bincrafters/stable", \
        "boost_lexical_cast/1.65.1@bincrafters/stable", \
        "boost_local_function/1.65.1@bincrafters/stable", \
        "boost_locale/1.65.1@bincrafters/stable", \
        "boost_lockfree/1.65.1@bincrafters/stable", \
        "boost_log/1.65.1@bincrafters/stable", \
        "boost_logic/1.65.1@bincrafters/stable", \
        "boost_math/1.65.1@bincrafters/stable", \
        "boost_metaparse/1.65.1@bincrafters/stable", \
        "boost_move/1.65.1@bincrafters/stable", \
        "boost_mpi/1.65.1@bincrafters/stable", \
        "boost_mpl/1.65.1@bincrafters/stable", \
        "boost_msm/1.65.1@bincrafters/stable", \
        "boost_multi_array/1.65.1@bincrafters/stable", \
        "boost_multi_index/1.65.1@bincrafters/stable", \
        "boost_multiprecision/1.65.1@bincrafters/stable", \
        "boost_numeric_conversion/1.65.1@bincrafters/stable", \
        "boost_numeric_interval/1.65.1@bincrafters/stable", \
        "boost_numeric_odeint/1.65.1@bincrafters/stable", \
        "boost_numeric_ublas/1.65.1@bincrafters/stable", \
        "boost_optional/1.65.1@bincrafters/stable", \
        "boost_parameter/1.65.1@bincrafters/stable", \
        "boost_phoenix/1.65.1@bincrafters/stable", \
        "boost_poly_collection/1.65.1@bincrafters/stable", \
        "boost_polygon/1.65.1@bincrafters/stable", \
        "boost_pool/1.65.1@bincrafters/stable", \
        "boost_predef/1.65.1@bincrafters/stable", \
        "boost_preprocessor/1.65.1@bincrafters/stable", \
        "boost_process/1.65.1@bincrafters/stable", \
        "boost_program_options/1.65.1@bincrafters/stable", \
        "boost_property_map/1.65.1@bincrafters/stable", \
        "boost_property_tree/1.65.1@bincrafters/stable", \
        "boost_proto/1.65.1@bincrafters/stable", \
        "boost_ptr_container/1.65.1@bincrafters/stable", \
        "boost_python/1.65.1@bincrafters/stable", \
        "boost_qvm/1.65.1@bincrafters/stable", \
        "boost_random/1.65.1@bincrafters/stable", \
        "boost_range/1.65.1@bincrafters/stable", \
        "boost_ratio/1.65.1@bincrafters/stable", \
        "boost_rational/1.65.1@bincrafters/stable", \
        "boost_regex/1.65.1@bincrafters/stable", \
        "boost_scope_exit/1.65.1@bincrafters/stable", \
        "boost_serialization/1.65.1@bincrafters/stable", \
        "boost_signals/1.65.1@bincrafters/stable", \
        "boost_signals2/1.65.1@bincrafters/stable", \
        "boost_smart_ptr/1.65.1@bincrafters/stable", \
        "boost_sort/1.65.1@bincrafters/stable", \
        "boost_spirit/1.65.1@bincrafters/stable", \
        "boost_stacktrace/1.65.1@bincrafters/stable", \
        "boost_statechart/1.65.1@bincrafters/stable", \
        "boost_static_assert/1.65.1@bincrafters/stable", \
        "boost_system/1.65.1@bincrafters/stable", \
        "boost_test/1.65.1@bincrafters/stable", \
        "boost_thread/1.65.1@bincrafters/stable", \
        "boost_throw_exception/1.65.1@bincrafters/stable", \
        "boost_timer/1.65.1@bincrafters/stable", \
        "boost_tokenizer/1.65.1@bincrafters/stable", \
        "boost_tti/1.65.1@bincrafters/stable", \
        "boost_tuple/1.65.1@bincrafters/stable", \
        "boost_type_erasure/1.65.1@bincrafters/stable", \
        "boost_type_index/1.65.1@bincrafters/stable", \
        "boost_type_traits/1.65.1@bincrafters/stable", \
        "boost_typeof/1.65.1@bincrafters/stable", \
        "boost_units/1.65.1@bincrafters/stable", \
        "boost_unordered/1.65.1@bincrafters/stable", \
        "boost_utility/1.65.1@bincrafters/stable", \
        "boost_uuid/1.65.1@bincrafters/stable", \
        "boost_variant/1.65.1@bincrafters/stable", \
        "boost_vmd/1.65.1@bincrafters/stable", \
        "boost_wave/1.65.1@bincrafters/stable", \
        "boost_winapi/1.65.1@bincrafters/stable", \
        "boost_xpressive/1.65.1@bincrafters/stable"
